export const env = {
  PORT: 'PORT',
  USER_GRPC_SERVER_URL: 'USER_GRPC_SERVER_URL',
  DISCOVERY_GRPC_SERVER_URL: 'DISCOVERY_GRPC_SERVER_URL',
  INTERACTION_GRPC_SERVER_URL: 'INTERACTION_GRPC_SERVER_URL',
  MONGODB_URI: 'MONGODB_URI',
};
