export const env = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  USER_GRPC_SERVER_URL: 'USER_GRPC_SERVER_URL',
  DISCOVERY_GRPC_SERVER_URL: 'DISCOVERY_GRPC_SERVER_URL',
  INTERACTION_GRPC_SERVER_URL: 'INTERACTION_GRPC_SERVER_URL',
  MONGODB_URI: 'MONGODB_URI',
  KAFKA_BROKER_URL: 'KAFKA_BROKER_URL',
  KAFKA_USERNAME: 'KAFKA_USERNAME',
  KAFKA_PASSWORD: 'KAFKA_PASSWORD',
};
