export const env = {
  PORT: 'PORT',
  USER_GRPC_SERVER_URL: 'USER_GRPC_SERVER_URL',
  MONGODB_URI: 'MONGODB_URI',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
};
