auth:
  rootUser: admin
  rootPassword: minioadmin

defaultBuckets: "loki-chunks,loki-ruler,loki-admin"
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m