export const env = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  GRPC_PORT: 'GRPC_PORT',
  MONGODB_URI: 'MONGODB_URI',
  JWT_SECRET: 'JWT_SECRET',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  KAFKA_BROKER_URL: 'KAFKA_BROKER_URL',
  KAFKA_USERNAME: 'KAFKA_USERNAME',
  KAFKA_PASSWORD: 'KAFKA_PASSWORD',
};
