apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "4000"
            - name: ALLOWED_ORIGINS
              value: "http://localhost:3000,http://localhost:3001"
            - name: AUTH_SERVER_URL
              value: "http://auth-service:3001"
            - name: USER_SERVER_URL
              value: "http://user-service:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30080
