apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4001"
            - name: APP_URL
              value: "https://i4you.local.net"
            - name: USER_GRPC_SERVER_URL
              value: "user-service:50051"
            - name: JWT_SECRET
              value: your_jwt_secret
            - name: JWT_EXPIRES_IN
              value: 15m
            - name: MONGODB_URI
              value: "mongodb+srv://rahilsardar234:NOKCk3dcykTN0P32@i4you-cluster.kdpj0cj.mongodb.net/I4You-userDB"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 4001
      targetPort: 4001
