apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: chat-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4003
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4003"
            - name: MONGODB_URI
              value: "mongodb+srv://rahilsardar234:NOKCk3dcykTN0P32@i4you-cluster.kdpj0cj.mongodb.net/I4You-chatDB"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  type: ClusterIP
  selector:
    app: chat-service
  ports:
    - port: 4003
      targetPort: 4003
