apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
        version: v1
    spec:
      containers:
        - name: discovery-service
          image: discovery-service-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4010
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "4010"
            - name: GRPC_PORT
              value: "50052"
            - name: MONGODB_URI
              value: "mongodb+srv://rahilsardar234:NOKCk3dcykTN0P32@i4you-cluster.kdpj0cj.mongodb.net/I4You-userDB"
            - name: REDIS_HOST
              value: "redis.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "password"
            - name: ES_URL
              value: "http://elastic-es-http.elastic-system.svc.cluster.local:9200"
            - name: ES_API_KEY
              value: "OWFPT2pwZ0JzRmNxVXhoam0wQ0E6bzNvZ1QtcnFoTFAyVjF2VWZoTWdnUQ=="

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: discovery-service
  ports:
    - name: http
      port: 4010
      targetPort: 4010
    - name: grpc
      port: 50052
      targetPort: 50052
