apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PUBLIC_APP_URL
              value: "https://i4you.local.net"
            - name: NEXT_PUBLIC_API_URL
              value: "https://i4you.local.net"
            - name: NEXT_PRIVATE_API_URL
              value: "http://gateway-server:4000"
            - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
              value: "802008925355-91g201jet474r07rah4if65gsn75251l.apps.googleusercontent.com"
            - name: NEXT_PRIVATE_JWT_SECRET
              value: "your_jwt_secret"
            - name: NEXT_PUBLIC_WEB_SOCKET_URL
              value: "wss://i4you.local.net"
            - name: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
              value: "AIzaSyDnetUxIAKDv-8s2yAcLD01azNlu_qG-j8"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30050