apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: frontend-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          #          resources:
          #            requests:
          #              cpu: "100m"
          #              memory: "128Mi"
          #            limits:
          #              cpu: "1000m"
          #              memory: "2Gi"
          #
          #          livenessProbe:
          #            httpGet:
          #              path: /
          #              port: 3000
          #            initialDelaySeconds: 5
          #            periodSeconds: 10
          #
          #          readinessProbe:
          #            httpGet:
          #              path: /
          #              port: 3000
          #            initialDelaySeconds: 3
          #            periodSeconds: 5
          env:
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PRIVATE_API_URL
              value: "https://i4you.local.net"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: NEXT_PRIVATE_JWT_SECRET
              value: "your_jwt_secret"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000

#---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: frontend-hpa
#  namespace: app
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: frontend
#  minReplicas: 1
#  maxReplicas: 10
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 80
#    - type: Resource
#      resource:
#        name: memory
#        target:
#          type: Utilization
#          averageUtilization: 80