apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: gateway-server-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "4000"
            - name: ALLOWED_ORIGINS
              value: "http://localhost:3000,http://localhost:3001"
            - name: AUTH_SERVER_URL
              value: "http://auth-service:4001"
            - name: USER_SERVER_URL
              value: "http://user-service:4002"
            - name: JWT_SECRET
              value: "your_jwt_secret"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  type: NodePort
  selector:
    app: gateway-server
  ports:
    - port: 4000
      targetPort: 4000