apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: user.events
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: user.events
  partitions: 1
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: match.events
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: match.events
  partitions: 1
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: notification.events
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: notification.events
  partitions: 1
  replicas: 1