apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4006
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4006"
            - name: KAFKAJS_NO_PARTITIONER_WARNING
              value: "1"
            - name: MONGODB_URI
              value: "mongodb+srv://rahilsardar234:NOKCk3dcykTN0P32@i4you-cluster.kdpj0cj.mongodb.net/I4You-notificationDB"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 4006
      targetPort: 4006
