export const env = {
  PORT: 'PORT',
  ALLOWED_ORIGINS: 'ALLOWED_ORIGINS',
  AUTH_SERVER_URL: 'AUTH_SERVER_URL',
  USER_SERVER_URL: 'USER_SERVER_URL',
  MEDIA_SERVER_URL: 'MEDIA_SERVER_URL',
  JWT_SECRET: 'JWT_SECRET',
};
