apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
        kraftMetadata: shared

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      process.roles: broker,controller
      node.id: 0
      controller.quorum.voters: "0@kafka-cluster-kafka-0.kafka-cluster-kafka-brokers.kafka.svc:9093"
      listeners: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      advertised.listeners: EXTERNAL://localhost:9092
      inter.broker.listener.name: PLAINTEXT
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: { }
    userOperator: { }