services:

  auth-service:
    image: auth-service-image
    pull_policy: never
    build:
      context: ./apps/services/auth-service
      dockerfile: Dockerfile.dev
      additional_contexts:
        root: ./
    volumes:
      - ./apps/services/auth-service:/app/apps/services/auth-service
      - /app/apps/services/auth-service/node_modules
      - ./packages:/app/packages
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=${AUTH_HTTP_PORT}
      - APP_URL=https://i4you.local.net
      - USER_GRPC_SERVER_URL=user-service:${USER_GRPC_PORT}
      - MONGODB_URI=mongodb://host.docker.internal:27017/I4you-userDB
    env_file:
      - ./apps/services/auth-service/.env
    networks:
      - app-network

  user-service:
    image: user-service-image
    pull_policy: never
    build:
      context: ./apps/services/user-service
      dockerfile: Dockerfile.dev
      additional_contexts:
        root: ./
    volumes:
      - ./apps/services/user-service:/app/apps/services/user-service
      - /app/apps/services/auth-service/node_modules
      - ./packages:/app/packages
    environment:
      - NODE_ENV=development
      - PORT=${USER_HTTP_PORT}
      - GRPC_PORT=${USER_GRPC_PORT}
      - MONGODB_URI=mongodb://host.docker.internal:27017/I4you-userDB
    env_file:
      - ./apps/services/user-service/.env
    networks:
      - app-network

  media-service:
    image: media-service-image
    pull_policy: never
    build:
      context: ./apps/services/media-service
      dockerfile: Dockerfile.dev
      additional_contexts:
        root: ./
    volumes:
      - ./apps/services/media-service:/app/apps/services/media-service
      - /app/apps/services/media-service/node_modules
      - ./packages:/app/packages
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=${MEDIA_HTTP_PORT}
      - USER_GRPC_SERVER_URL=user-service:${USER_GRPC_PORT}
    env_file:
      - ./apps/services/media-service/.env
    networks:
      - app-network

  #  chat-service:
  #    build: apps/services/chat-service
  #    ports:
  #      - "6000:6000"
  #    volumes:
  #      - ./apps/services/chat-service:/app
  #      - /app/node_modules
  #    depends_on:
  #      - user-service

  gateway-server:
    image: gateway-server-image
    pull_policy: never
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile.dev
      additional_contexts:
        root: ./
    ports:
      - "${GATEWAY_HTTP_PORT}:${GATEWAY_HTTP_PORT}"
      - "9464:9464"
    volumes:
      - ./apps/gateway:/app/apps/gateway
      - /app/node_modules
      - /app/apps/services/auth-service/node_modules
      - ./packages:/app/packages
    environment:
      - NODE_ENV=development
      - PORT=${GATEWAY_HTTP_PORT}
      - USER_SERVER_URL=http://user-service:${USER_HTTP_PORT}
      - AUTH_SERVER_URL=http://auth-service:${AUTH_HTTP_PORT}
      - MEDIA_SERVER_URL=http://media-service:${MEDIA_HTTP_PORT}
      - ALLOWED_ORIGINS=http://localhost:3000,https://localhost:3000,https://i4you.local.net,http://i4you.local.net
    env_file:
      - ./apps/gateway/.env
    depends_on:
      - user-service
      - auth-service
      - media-service
    networks:
      - app-network

  frontend:
    image: frontend-image
    pull_policy: never
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
      additional_contexts:
        root: ./
    volumes:
      - /app/node_modules
      - /app/apps/frontend/node_modules
      - ./apps/frontend:/app/apps/frontend
      - ./packages:/app/packages
    environment:
      - NODE_ENV=development
    env_file:
      - apps/frontend/.env.development
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    #    build:
    #      context: ./apps/nginx
    #      dockerfile: Dockerfile.dev
    #    image: i4you-nginx
    image: nginx:latest
    container_name: i4you-nginx
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gateway-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
