services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./apps/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "5050:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
      - "3100:3100/udp"
      - "3100:3100/tcp"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  grafana-storage:
    driver: local

networks:
  app-network:
    driver: bridge