services:
  auth-service:
    image: asia-south1-docker.pkg.dev/i4you-457707/i4you-repo/auth-service-image:v0.0.6
    pull_policy: never
    build:
      platforms:
        - linux/amd64
      context: ./apps/services/auth-service
      dockerfile: Dockerfile
      additional_contexts:
        root: ./
    networks:
      - app-network

  user-service:
    image: asia-south1-docker.pkg.dev/i4you-457707/i4you-repo/user-service-image:v0.0.2
    pull_policy: never
    build:
      platforms:
        - linux/amd64
      context: ./apps/services/user-service
      dockerfile: Dockerfile
      additional_contexts:
        root: ./
    networks:
      - app-network

  media-service:
    image: asia-south1-docker.pkg.dev/i4you-457707/i4you-repo/media-service-image:v0.0.1
    pull_policy: never
    build:
      platforms:
        - linux/amd64
      context: ./apps/services/media-service
      dockerfile: Dockerfile
      additional_contexts:
        root: ./
    volumes:
      - ./apps/services/media-service:/app/apps/services/media-service
      - /app/apps/services/media-service/node_modules
      - ./packages:/app/packages
    networks:
      - app-network

  gateway-server:
    image: asia-south1-docker.pkg.dev/i4you-457707/i4you-repo/gateway-server-image:v0.0.1
    pull_policy: never
    build:
      platforms:
        - linux/amd64
      context: ./apps/gateway
      dockerfile: Dockerfile
      additional_contexts:
        root: ./
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - auth-service
    networks:
      - app-network

  frontend:
    image: asia-south1-docker.pkg.dev/i4you-457707/i4you-repo/frontend-image:v0.0.2
    pull_policy: never
    build:
      platforms:
        - linux/amd64
      context: ./apps/frontend
      dockerfile: Dockerfile
      additional_contexts:
        root: ./
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=https://i4you.ddns.net
      - NEXT_PUBLIC_API_URL=https://i4you.ddns.net
      - NEXT_PRIVATE_API_URL=http://gateway-server:4000
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=802008925355-dtft0lvcs3af92jjcqqbbitudp4et8ts.apps.googleusercontent.com
      - NEXT_PRIVATE_JWT_SECRET=your_jwt_secret
      - NEXT_PUBLIC_WEB_SOCKET_URL=wss://i4you.ddns.net
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyDnetUxIAKDv-8s2yAcLD01azNlu_qG-j8
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
