#nonk8s
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: i4you
build:
  artifacts:
    - image: validate-service-image
      context: apps/services/validate-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: user-service-image
      context: apps/services/user-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: auth-service-image
      context: apps/services/auth-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: media-service-image
      context: apps/services/media-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: chat-service-image
      context: apps/services/chat-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: frontend-image
      context: apps/frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: socket-nginx-image
      context: apps/nginx
      docker:
        dockerfile: Dockerfile.dev
  local:
    push: false
    useBuildkit: true
    concurrency: 0

manifests:
  rawYaml:
    - k8s/dev/validate-service.yaml
    - k8s/dev/user-service.yaml
    - k8s/dev/auth-service.yaml
    - k8s/dev/media-service.yaml
    - k8s/dev/chat-service.yaml
    - k8s/dev/frontend.yaml
    - k8s/dev/nginx-socket-proxy.yaml
    - k8s/dev/traefik-ingress.yaml
    - k8s/dev/traefik-strip-path-middleware.yaml
    - k8s/dev/traefik-validate-middleware.yaml
