#nonk8s
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: i4you
build:
  artifacts:
    - image: validate-service-image
      context: apps/services/validate-service
      sync:
        manual:
          - src: src/**/*
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: user-service-image
      context: apps/services/user-service
      sync:
        manual:
          - src: src/**/*
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: auth-service-image
      context: apps/services/auth-service
      sync:
        manual:
          - src: src/**/*
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: media-service-image
      context: apps/services/media-service
      sync:
        manual:
          - src: src/**/*
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: match-service-image
      context: apps/services/match-service
      sync:
        manual:
          - src: src/**/*
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: chat-service-image
      context: apps/services/chat-service
      sync:
        manual:
          - src: src/**/*
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: frontend-image
      context: apps/frontend
      sync:
        manual:
          - src: src/**/*
            dest: .
      docker:
        dockerfile: Dockerfile.dev
    - image: socket-nginx-image
      context: apps/nginx
      docker:
        dockerfile: Dockerfile.dev
  local:
    push: false
    useBuildkit: true
    concurrency: 0
manifests:
  helm:
    releases:
      - name: strimzi-kafka-operator
        remoteChart: strimzi/strimzi-kafka-operator
        namespace: kafka
        createNamespace: true
        version: 0.46.1
        setValues:
          watchAnyNamespace: false
          watchNamespaces[0]: kafka
  rawYaml:
    - k8s/dev/kafka-namespace.yaml
    - k8s/dev/validate-service.yaml
    - k8s/dev/user-service.yaml
    - k8s/dev/auth-service.yaml
    - k8s/dev/media-service.yaml
    - k8s/dev/match-service.yaml
    - k8s/dev/chat-service.yaml
    - k8s/dev/frontend.yaml
    - k8s/dev/nginx-socket-proxy.yaml
    - k8s/dev/traefik-ingress.yaml
    - k8s/dev/traefik-strip-path-middleware.yaml
    - k8s/dev/traefik-validate-middleware.yaml
    - k8s/dev/redis.yaml
    - k8s/dev/kafka-kraft.yaml

profiles:
  - name: strimzi
    build:
      artifacts:
      - image: validate-service-image
        context: apps/services/validate-service
        docker:
          dockerfile: Dockerfile.dev
      local:
        push: false
        useBuildkit: true
        concurrency: 0
    manifests:
      rawYaml:
          - k8s/dev/kafka-namespace.yaml
      helm:
        releases:
          - name: strimzi-kafka-operator
            remoteChart: strimzi/strimzi-kafka-operator
            namespace: kafka
            createNamespace: false
            version: 0.46.1
            setValues:
              watchAnyNamespace: false
              watchNamespaces[0]: kafka

  - name: production
    build:
      artifacts:
        - image: asia-south1-docker.pkg.dev/i4you-457707/i4you-repo/validate-service-image
          context: apps/services/validate-service
          docker:
            dockerfile: Dockerfile
#        - image: user-service-image
#          context: apps/services/user-service
#          docker:
#            dockerfile: Dockerfile
#        - image: auth-service-image
#          context: apps/services/auth-service
#          docker:
#            dockerfile: Dockerfile
#        - image: media-service-image
#          context: apps/services/media-service
#          docker:
#            dockerfile: Dockerfile
#        - image: chat-service-image
#          context: apps/services/chat-service
#          docker:
#            dockerfile: Dockerfile
#        - image: frontend-image
#          context: apps/frontend
#          docker:
#            dockerfile: Dockerfile
#        - image: socket-nginx-image
#          context: apps/nginx
#          docker:
#            dockerfile: Dockerfile
      local:
        push: true
        useBuildkit: true
        concurrency: 0
    manifests:
      rawYaml:
        - k8s/prod/validate-service.yaml