#nonk8s
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: i4you
profiles:
  - name: crds
    deploy:
      kubectl:
        hooks:
          before:
            - host:
                command:
                  - kubectl
                  - apply
                  - --server-side
                  - --force-conflicts
                  - -f
                  - https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml
            - host:
                command:
                  - kubectl
                  - apply
                  - --server-side
                  - --force-conflicts
                  - -f
                  - https://github.com/grafana/grafana-operator/releases/download/v5.18.0/crds.yaml
    manifests:
      rawYaml:
        - https://download.elastic.co/downloads/eck/3.1.0/crds.yaml
        - https://raw.githubusercontent.com/traefik/traefik/v3.4/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
        - https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.47.0/strimzi-crds-0.47.0.yaml
        - https://raw.githubusercontent.com/grafana/grafana-operator/master/deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanas.yaml
        - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.84.0/stripped-down-crds.yaml
        - https://raw.githubusercontent.com/grafana/grafana-operator/master/deploy/helm/grafana-operator/crds/grafana.integreatly.org_grafanas.yaml

  - name: setup
    deploy:
      kubectl:
        hooks:
          after:
            - host:
                command:
                  - kubectl
                  - apply
                  - -f
                  - k8s/dev/hashicorp/vault/job.yaml
    manifests:
      rawYaml:
        - k8s/dev/elastic/namespace.yaml
        - k8s/dev/traefik/namespace.yaml
        - k8s/dev/kafka/kafka-namespace.yaml
        - k8s/dev/hashicorp/vault/namespace.yaml
        - k8s/dev/hashicorp/vault/vault-root-secret.yaml
        - k8s/dev/hashicorp/vault/vault-unseal-keys.yaml
        - k8s/dev/hashicorp/vault/vault-ingress.yaml
        - k8s/dev/hashicorp/vault/storage-class.yaml
        - k8s/dev/hashicorp/vault/vault-cluster-store.yaml
        - k8s/dev/hashicorp/vault/job.yaml
        - https://download.elastic.co/downloads/eck/3.1.0/operator.yaml
        - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.8.0/components.yaml
        - k8s/dev/kafka/kafka-storage.yaml
        - k8s/dev/kafka/kafka-kraft.yaml
        - k8s/dev/elastic/storage-class.yaml
        - k8s/dev/elastic/elasticsearch.yaml
        - k8s/dev/kibana/kibana.yaml
        - k8s/dev/kibana/ingress.yaml
        - k8s/dev/kibana/kibana-user.yaml
        - k8s/dev/redis.yaml
      helm:
        releases:
          - name: vault
            remoteChart: hashicorp/vault
            namespace: vault
            createNamespace: true
            version: 0.30.1
            valuesFiles:
              - k8s/dev/hashicorp/vault/values.yaml
          - name: external-secrets
            remoteChart: external-secrets-operator/external-secrets
            version: 0.19.1
            setValues:
              installCRDs: false
          - name: strimzi-kafka-operator
            remoteChart: strimzi/strimzi-kafka-operator
            namespace: kafka
            createNamespace: true
            version: 0.46.1
            setValues:
              watchAnyNamespace: false
              watchNamespaces[0]: kafka
          - name: traefik
            remoteChart: traefik/traefik
            namespace: traefik
            createNamespace: true
            valuesFiles:
              - k8s/dev/traefik/values.yaml

  - name: dev
    build:
      artifacts:
        - image: validate-service-image
          context: apps/services/validate-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: user-service-image
          context: apps/services/user-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: auth-service-image
          context: apps/services/auth-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: media-service-image
          context: apps/services/media-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: match-service-image
          context: apps/services/match-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: chat-service-image
          context: apps/services/chat-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: signaling-service-image
          context: apps/services/signaling-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: notification-service-image
          context: apps/services/notification-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: moderation-service-image
          context: apps/services/moderation-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: interaction-service-image
          context: apps/services/interaction-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: discovery-service-image
          context: apps/services/discovery-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: payment-service-image
          context: apps/services/payment-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: es-worker-service-image
          context: apps/services/es-worker-service
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: frontend-image
          context: apps/frontend
          sync:
            manual:
              - src: src/**/*
                dest: .
          docker:
            dockerfile: Dockerfile.dev
        - image: socket-nginx-image
          context: apps/nginx
          docker:
            dockerfile: Dockerfile.dev
      local:
        push: false
        useBuildkit: true
        concurrency: 0
    manifests:
      rawYaml:
        - k8s/dev/app-namespace.yaml
        - k8s/dev/secrets/vault-secrets.yaml
        - k8s/dev/kafka/kafka-topics.yaml
        - k8s/dev/i4you-cert-secret.yaml
        - k8s/dev/traefik/traefik-validate-middleware.yaml
        - k8s/dev/traefik/traefik-strip-path-middleware.yaml
        - k8s/dev/services/validate-service.yaml
        - k8s/dev/services/user-service.yaml
        - k8s/dev/services/auth-service.yaml
        - k8s/dev/services/media-service.yaml
        - k8s/dev/services/match-service.yaml
        - k8s/dev/services/chat-service.yaml
        - k8s/dev/services/signaling-service.yaml
        - k8s/dev/services/discovery-service.yaml
        - k8s/dev/services/es-worker-service.yaml
        - k8s/dev/services/moderation-service.yaml
        - k8s/dev/services/notification-service.yaml
        - k8s/dev/services/interaction-service.yaml
        - k8s/dev/services/payment-service.yaml
        - k8s/dev/services/stripe-webhook-handler.yaml
        - k8s/dev/services/frontend.yaml
        - k8s/dev/nginx-socket-proxy.yaml
        - k8s/dev/traefik/traefik-ingress.yaml

  - name: production
    build:
      artifacts:
        - image: asia-south1-docker.pkg.dev/i4you-457707/i4you-repo/validate-service-image
          context: apps/services/validate-service
          docker:
            dockerfile: Dockerfile
      #        - image: user-service-image
      #          context: apps/services/user-service
      #          docker:
      #            dockerfile: Dockerfile
      #        - image: auth-service-image
      #          context: apps/services/auth-service
      #          docker:
      #            dockerfile: Dockerfile
      #        - image: media-service-image
      #          context: apps/services/media-service
      #          docker:
      #            dockerfile: Dockerfile
      #        - image: chat-service-image
      #          context: apps/services/chat-service
      #          docker:
      #            dockerfile: Dockerfile
      #        - image: frontend-image
      #          context: apps/frontend
      #          docker:
      #            dockerfile: Dockerfile
      #        - image: socket-nginx-image
      #          context: apps/nginx
      #          docker:
      #            dockerfile: Dockerfile
      local:
        push: true
        useBuildkit: true
        concurrency: 0
    manifests:
      rawYaml:
        - k8s/prod/validate-service.yamls

  - name: monitoring
    manifests:
      rawYaml:
        - k8s/dev/monitoring/namespace.yaml
        - k8s/dev/monitoring/prometheus-ingress.yaml
        - k8s/dev/monitoring/grafana-ingress.yaml
        - k8s/dev/monitoring/grafana/grafana.yaml
        - k8s/dev/monitoring/grafana/loki-datasource.yaml
      helm:
        releases:
          - name: grafana-operator
            remoteChart: grafana/grafana-operator
            namespace: monitoring
            createNamespace: true
          #          - name: grafana-old
          #            remoteChart: grafana/grafana
          #            namespace: monitoring
          #            createNamespace: true
          #            valuesFiles:
          #              - k8s/dev/monitoring/grafana/values.yaml
          #          - name: promtail
          #            remoteChart: grafana/promtail
          #            namespace: monitoring
          #            createNamespace: true
          #            valuesFiles:
          #              - k8s/dev/monitoring/promtail/values.yaml
          - name: loki
            remoteChart: grafana/loki
            namespace: monitoring
            createNamespace: true
            valuesFiles:
              - k8s/dev/monitoring/loki/values.yaml
          - name: minio
            remoteChart: bitnami/minio
            namespace: monitoring
            createNamespace: true
            valuesFiles:
              - k8s/dev/monitoring/minio/values.yaml
          - name: alloy
            remoteChart: grafana/alloy
            namespace: monitoring
            createNamespace: true
            valuesFiles:
              - k8s/dev/monitoring/alloy/values.yaml
          - name: prometheus
            remoteChart: prometheus-community/kube-prometheus-stack
            namespace: monitoring
            createNamespace: true
            valuesFiles:
              - k8s/dev/monitoring/prometheus/values.yaml

  - name: istio
    manifests:
      rawYaml:
        - https://raw.githubusercontent.com/istio/istio/release-1.21/samples/addons/prometheus.yaml
        - k8s/dev/istio/namespace.yaml
      helm:
        releases:
          - name: istiod
            remoteChart: istiod
            repo: https://istio-release.storage.googleapis.com/charts
            namespace: istio-system
            createNamespace: true
          - name: kiali-server
            remoteChart: kiali/kiali-server
            namespace: istio-system
            createNamespace: true
            setValues:
              auth:
                strategy: "anonymous"
