FROM node:18-alpine AS builder

WORKDIR /app

COPY --from=root package*.json pnpm*.yaml turbo.json ./
COPY --from=root packages packages

COPY package.json ./apps/frontend/

RUN corepack enable && pnpm install --frozen-lockfile

COPY . ./apps/frontend

EXPOSE 3000

CMD ["pnpm", "run", "--filter=frontend", "dev"]
