apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
        version: v1
    spec:
      containers:
        - name: discovery-service
          image: asia-south1-docker.pkg.dev/i4you-472205/i4you-repo/discovery-service-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4010
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "4010"
            - name: GRPC_PORT
              value: "50052"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: MONGODB_URI
            - name: ES_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: ES_URL
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: ES_USERNAME
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: ES_PASSWORD
            - name: ES_MAX_RETRY
              value: "5"
            - name: ES_REQUEST_TIMEOUT
              value: "60000"

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: discovery-service
  ports:
    - name: http
      port: 4010
      targetPort: 4010
    - name: grpc
      port: 50052
      targetPort: 50052
