apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: asia-south1-docker.pkg.dev/i4you-472205/i4you-repo/frontend-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              value: "https://i4you.ddns.net"
            - name: NEXT_PUBLIC_APP_URL
              value: "https://i4you.ddns.net"
            - name: NEXT_PRIVATE_API_URL
              value: "https://i4you.ddns.net"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: NEXT_PRIVATE_JWT_SECRET
              value: "your_jwt_secret"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
