apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
        version: v1
    spec:
      containers:
        - name: match-service
          image: asia-south1-docker.pkg.dev/i4you-472205/i4you-repo/match-service-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4005
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4005"
            - name: USER_GRPC_SERVER_URL
              value: "user-service:50051"
            - name: DISCOVERY_GRPC_SERVER_URL
              value: "discovery-service:50052"
            - name: INTERACTION_GRPC_SERVER_URL
              value: "interaction-service:50051"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: MONGODB_URI
            - name: KAFKA_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: KAFKA_BROKER_URL
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: KAFKA_USERNAME
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: KAFKA_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: match-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: match-service
  ports:
    - name: http
      port: 4005
      targetPort: 4005
    - name: grpc
      port: 50055
      targetPort: 50055
