apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation-service
  template:
    metadata:
      labels:
        app: moderation-service
        version: v1
    spec:
      containers:
        - name: moderation-service
          image: asia-south1-docker.pkg.dev/i4you-472205/i4you-repo/moderation-service-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4012
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "4012"
            - name: GRPC_PORT
              value: "50052"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: MONGODB_URI
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: CLOUDINARY_API_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: moderation-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: moderation-service
  ports:
    - name: http
      port: 4012
      targetPort: 4012
    - name: grpc
      port: 50052
      targetPort: 50052
