apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        version: v1
    spec:
      containers:
        - name: notification-service
          image: asia-south1-docker.pkg.dev/i4you-472205/i4you-repo/notification-service-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4006
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4006"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: MONGODB_URI
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: REDIS_PASSWORD
            - name: KAFKA_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: KAFKA_BROKER_URL
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: KAFKA_USERNAME
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: KAFKA_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 4006
      targetPort: 4006
