apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
        version: v1
    spec:
      containers:
        - name: subscription-service
          image: asia-south1-docker.pkg.dev/i4you-472205/i4you-repo/subscription-service-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4010
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4010"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: MONGODB_URI

---
apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: subscription-service
  ports:
    - name: http
      port: 4010
      targetPort: 4010
