apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: asia-south1-docker.pkg.dev/i4you-457707/i4you-repo/auth-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          env:
            - name: NODE_ENV
              value: "development"
            - name: ALLOWED_ORIGINS
              value: "http://localhost:3000,http://localhost:3001"
            - name: AUTH_SERVER_URL
              value: "http://auth-service:3001"
            - name: USER_SERVER_URL
              value: "http://user-service:3000"
            - name: PORT
              value: "4001"
            - name: USER_GRPC_SERVER_URL
              value: "localhost:50051"
            - name: JWT_SECRET
              value: your_jwt_secret
            - name: JWT_EXPIRES_IN
              value: 15m
            - name: MONGODB_URI
              value: "mongodb+srv://rahilsardar234:tPPNaEcGk980awe2@i4you-cluster.kdpj0cj.mongodb.net"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 4001
      targetPort: 4001
      nodePort: 30080
