apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: asia-south1-docker.pkg.dev/i4you-457707/i4you-repo/user-service-image:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4002"
            - name: AUTH_SERVER_URL
              value: "http://auth-service:3001"
            - name: USER_SERVER_URL
              value: "http://user-service:3000"
            - name: GRPC_PORT
              value: "50051"
            - name: MONGODB_URI
              value: "mongodb+srv://rahilsardar234:tPPNaEcGk980awe2@i4you-cluster.kdpj0cj.mongodb.net"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - port: 4002
      targetPort: 4002
      nodePort: 30090
