FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY --from=root /package*.json /pnpm*.yaml ./
COPY --from=root /packages /app/packages

COPY package.json /app/apps/services/validate-service/

RUN pnpm install --filter=validate-service

COPY . /app/apps/services/validate-service

CMD ["pnpm", "run", "--filter=validate-service", "dev"]