services:

  order-service:
    build: order-service
    ports:
      - "4002:4002"
    volumes:
      - ./order-service:/app
      - /app/node_modules
    depends_on:
      - user-service
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    command: "npm run dev"

  user-service:
    build: ./user-service
    ports:
      - "50051:50051"
      - "3001:3001"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    command: "npm run dev"


networks:
  app-network:
    driver: bridge