FROM node:23-alpine

WORKDIR /app

RUN corepack enable

COPY --from=root /package.json /pnpm*.yaml ./
COPY --from=root /packages /app/packages

COPY . /app/apps/services/user-service

RUN pnpm install

CMD ["pnpm", "run", "--filter=user-service", "dev"]