FROM node:22-alpine

WORKDIR /repo

RUN corepack enable

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY tsconfig.json ./
COPY tsconfig.base.json ./
COPY eslint.config.mjs ./
COPY nx.json ./

COPY packages ./packages
COPY apps/services/user-service/package.json ./apps/services/user-service/

RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

COPY apps/services/user-service ./apps/services/user-service

ENTRYPOINT ["pnpm", "exec", "nx", "serve", "user-service"]
