export const env = {
  NODE_ENV: 'NODE_ENV',
  GRPC_PORT: 'GRPC_PORT',
  ES_URL: 'ES_URL',
  ES_USERNAME: 'ES_USERNAME',
  ES_PASSWORD: 'ES_PASSWORD',
  ES_MAX_RETRY: 'ES_MAX_RETRY',
  ES_REQUEST_TIMEOUT: 'ES_REQUEST_TIMEOUT',
};
