export const env = {
  NODE_ENV: 'NODE_ENV',
  GRPC_PORT: 'GRPC_PORT',
  ES_URL: 'ES_URL',
  ES_USERNAME: 'ES_USERNAME',
  ES_PASSWORD: 'ES_PASSWORD',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
};
