export const env = {
  NODE_ENV: 'NODE_ENV',
  GRPC_PORT: 'GRPC_PORT',
  ES_URL: 'ES_URL',
  ES_API_KEY: 'ES_API_KEY',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
};