FROM node:23-alpine

WORKDIR /app

RUN corepack enable

# Copy root-level package files from the additional 'root' context
COPY --from=root /package*.json /pnpm*.yaml ./
COPY --from=root /packages /app/packages
COPY --from=root /scripts /app/scripts

COPY . /app/apps/services/auth-service

RUN pnpm install --filter=auth-service

CMD ["pnpm", "run", "--filter=auth-service", "dev"]