FROM node:23-alpine

WORKDIR /app

RUN corepack enable

COPY --from=root /package*.json /pnpm*.yaml ./
COPY --from=root /packages /app/packages

COPY package.json /app/apps/services/auth-service/

RUN pnpm install

COPY . /app/apps/services/auth-service

CMD ["pnpm", "run", "--filter=auth-service", "dev"]