FROM node:22-alpine

WORKDIR /repo
RUN corepack enable

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY nx.json ./
COPY pnpm-lock.yaml ./

COPY packages ./packages
COPY apps/services/auth-service/package.json ./apps/services/auth-service/

RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install

COPY apps/services/auth-service ./apps/services/auth-service

ENTRYPOINT ["npx", "nx", "run", "auth-service:dev"]
