FROM node:22-alpine

WORKDIR /repo
RUN corepack enable

COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY nx.json ./
COPY eslint.config.mjs ./
COPY tsconfig.json ./
COPY tsconfig.base.json ./

COPY packages ./packages
COPY apps/services/template-service/package.json ./apps/services/template-service/

RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install

COPY apps/services/template-service ./apps/services/template-service

ENTRYPOINT ["npx", "nx", "serve", "template-service"]
