apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interaction-service
      version: v1
  template:
    metadata:
      labels:
        app: interaction-service
        version: v1
    spec:
      containers:
        - name: interaction-service
          image: interaction-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4002"
            - name: GRPC_PORT
              value: "50051"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: MONGODB_URI
            - name: REDIS_HOST
              value: "redis.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "password"
            - name: KAFKA_BROKER_URL
              value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_USERNAME
              value: "rahil"
            - name: KAFKA_PASSWORD
              value: "zWxJ2ttyrc4qCXwNX4U5XRMTVMFndIzn"

---
apiVersion: v1
kind: Service
metadata:
  name: interaction-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: interaction-service
  ports:
    - name: http
      port: 4002
      targetPort: 4002
    - name: grpc
      port: 50051
      targetPort: 50051
