apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
        version: v1
    spec:
      #      initContainers:
      #        - name: wait-for-kafka
      #          image: busybox
      #          command:
      #            - sh
      #            - -c
      #            - |
      #              echo "Waiting for Kafka DNS to resolve..."
      #              until nslookup kafka-cluster-kafka-brokers.kafka.svc.cluster.local; do
      #                echo "Still waiting for Kafka..."
      #                sleep 2
      #              done
      containers:
        - name: match-service
          image: match-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4005
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4005"
            - name: USER_GRPC_SERVER_URL
              value: "user-service:50051"
            - name: DISCOVERY_GRPC_SERVER_URL
              value: "discovery-service:50052"
            - name: INTERACTION_GRPC_SERVER_URL
              value: "interaction-service:50051"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: MONGODB_URI
            - name: KAFKA_BROKER_URL
              value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_USERNAME
              value: "rahil"
            - name: KAFKA_PASSWORD
              value: "zWxJ2ttyrc4qCXwNX4U5XRMTVMFndIzn"

---
apiVersion: v1
kind: Service
metadata:
  name: match-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: match-service
  ports:
    - name: http
      port: 4005
      targetPort: 4005
    - name: grpc
      port: 50055
      targetPort: 50055
