apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
        version: v1
    spec:
      containers:
        - name: media-service
          image: media-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4003
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4003"
            - name: REDIS_HOST
              value: "redis.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "password"
            - name: AWS_REGION
              value: "ap-south-1"
            - name: AWS_ACCESS_KEY_ID
              value: "ID"
            - name: AWS_SECRET_ACCESS_KEY
              value: "KEY"
            - name: AWS_BUCKET_NAME
              value: "i4you-bucket"
            - name: CLOUDINARY_CLOUD_NAME
              value: "snapcart-website"
            - name: CLOUDINARY_API_KEY
              value: "415286569897134"
            - name: CLOUDINARY_API_SECRET
              value: "cNEdzuyNazOMmXPLLMf_9kCNsDo"

---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: media-service
  ports:
    - port: 4003
      targetPort: 4003
