apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        version: v1
    spec:
      containers:
        - name: notification-service
          image: notification-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4006
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4006"
            - name: KAFKAJS_NO_PARTITIONER_WARNING
              value: "1"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: MONGODB_URI
            - name: REDIS_HOST
              value: "redis.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "password"
            - name: KAFKA_BROKER_URL
              value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_USERNAME
              value: "rahil"
            - name: KAFKA_PASSWORD
              value: "zWxJ2ttyrc4qCXwNX4U5XRMTVMFndIzn"

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 4006
      targetPort: 4006
