apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validate-service
  template:
    metadata:
      labels:
        app: validate-service
        version: v1
    spec:
      containers:
        - name: validate-service
          image: validate-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: APP_URL
              value: "https://i4you.ddns.net"
            - name: USER_GRPC_SERVER_URL
              value: "localhost:50051"
            - name: JWT_SECRET
              value: your_jwt_secret
            - name: JWT_EXPIRES_IN
              value: 15m
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: MONGODB_URI
            - name: REDIS_HOST
              value: "redis.redis.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: validate-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: validate-service
  ports:
    - port: 80
      targetPort: 5000
