export const env = {
    NODE_ENV: 'NODE_ENV',
    PORT: 'PORT',
    FRONTEND_URL: 'FRONTEND_URL',
    STRIPE_SECRET_KEY: 'STRIPE_SECRET_KEY',
    STRIPE_WEBHOOK_SECRET: 'STRIPE_WEBHOOK_SECRET',
    RAZORPAY_KEY_ID: 'RAZORPAY_KEY_ID',
    RAZORPAY_KEY_SECRET: 'RAZORPAY_KEY_SECRET',
};
