export const env = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  ES_URL: 'ES_URL',
  ES_USERNAME: 'ES_USERNAME',
  ES_PASSWORD: 'ES_PASSWORD',
  KAFKA_BROKER_URL: 'KAFKA_BROKER_URL',
  KAFKA_USERNAME: 'KAFKA_USERNAME',
  KAFKA_PASSWORD: 'KAFKA_PASSWORD',
};
