name: Build and Push Docker Images to Google Artifact Registry

on:
  workflow_run:
    workflows: ["Publish Packages to npm"]
    types: [completed]
    branches: [main]

jobs:
  build-and-push:
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build and Push Images
        run: |
          docker-compose -f docker-compose-prod.yaml build
          docker-compose -f docker-compose-prod.yaml push