name: Deploy to Production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/802008925355/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'gar-945@i4you-457707.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate Docker to GAR
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Deploy to Production using Skaffold
        run: skaffold run -p production