name: Publish Packages to npm

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/publish-packages.yaml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish valid packages
        run: |
          find packages -type f -name package.json | while read pkgfile; do
            pkgdir=$(dirname "$pkgfile")
            cd "$pkgdir"

            if ! grep -q '"name"' package.json || ! grep -q '"version"' package.json; then
              echo "Skipping $pkgdir (no name/version)"
              cd - > /dev/null
              continue
            fi

            PKG_NAME=$(node -p "require('./package.json').name")
            PKG_VERSION=$(node -p "require('./package.json').version")
            EXISTS=$(npm view $PKG_NAME@$PKG_VERSION version 2>/dev/null || echo "not-found")

            if [ "$EXISTS" = "not-found" ]; then
              echo "Publishing $PKG_NAME@$PKG_VERSION"
              npm publish --access public
            else
              echo "$PKG_NAME@$PKG_VERSION already exists. Skipping."
            fi

            cd - > /dev/null
          done
