export const env = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  APP_URL: 'APP_URL',
  USER_GRPC_SERVER_URL: 'USER_GRPC_SERVER_URL',
  MONGODB_URI: 'MONGODB_URI',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
};
